#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# 1 Chat
# 3 Calc
# 4 pdf & facultad
# 5 media
# 7, 8 terminales
# 9 firefox

bspc rule -a firefox desktop='^9' follow=on
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a Zathura desktop='^4' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a SpeedCrunch desktop='^3' follow=on
bspc rule -a Xournalpp desktop='^4' follow=on
bspc rule -a Microsoft Teams - Preview desktop='^1' follow=on
bspc rule -a Spotify desktop='^5' follow=on
