call plug#begin('~/.vim/plugged')

Plug 'elkowar/yuck.vim'

call plug#end()

command! -nargs=1 Wro w !sudo tee <args> 
"write to <args> file when on read only mode (:Wro foo.txt :Wro %)

syntax on

set background=dark
set tabstop=4
set softtabstop=4
set expandtab
colorscheme koehler
set nohlsearch

set scroll=10

set number

filetype indent on 

set lazyredraw

set wildmenu

set showmatch

set incsearch

set hidden
"Para cambiar de buffer sin escribir cambios

inoremap kj <C-C> 

vnoremap kj <C-C>

cnoremap kj <C-C>
"makes escape more comfortable

let mapleader = ","

vnoremap <leader>y "+y
nnoremap <leader>p "+p
nnoremap <leader>o "*p
"yanks and pastes to and from the clipboard register

nnoremap <leader>ev :vsp ~/.vimrc<cr>
"opens vimrc in a vertical split

nnoremap <leader>sv :so ~/.vimrc<cr>
"sources vimrc so any saved changes have effect on the current buffer

noremap <leader>t :sh<cr>

nnoremap <leader>u viw~

noremap <leader>w <c-w><c-w>

nnoremap <leader>lc :! pdflatex --jobname=texaux %<cr>
"compile latex file to view it

nnoremap <leader>lw :! pdflatex %<cr>
"compile latex file with its source name

nnoremap <leader>lv :! zathura texaux.pdf & disown<cr>
"opens the compiled pdf latex file in zathura

nnoremap <leader>b :bnext<cr>
"Cambio rapido al siguiente buffer

inoremap <C-e> <C-C>"+pa
"Permite pegar contenido del registro + en insert mode
